#Manage the team spawn settings:
spawns:
  spawnblue:
    x: 0
    y: 0
    z: 0
    pitch: -180
    yaw: 0
  spawnred:
    x: 0
    y: 0
    z: 0
    pitch: -180
    yaw: 0
  lobby:
    x: 0
    y: 0
    z: 0
    pitch: -180
    yaw: 0

#Manage the red team flag settings:
flag:
  x: 0
  y: 0
  z: 0

#Manage the blue team capture settings:
capture:
  x: 0
  y: 0
  z: 0

#Manage the database settings:
database:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "admin"
  password: "1234"