name: MarcWar
version: 0.0.1
description: A CTF Bukkit plugin for the Mindcrack Marathon event.
author: Favorlock

main: com.mcprohosting.plugins.marcwar.MarcWar
database: false

commands:
  setspawn:
    description: Set one of the spawn locations for the teams to the current location of the player.
    usage: /<command> <color>
  setflag:
    description: Set the red team flag to the block a player is looking at.
    usage: /<command>
  setcapture:
    description: Set the blue team capture point to the 1 block above the block a player is looking at.
    usage: /<command>
  setlobby:
    description: Set the lobby spawn.
    usage: /<command>
  startgame:
    description: Start the game.
    usage: /<command>
permissions:
  marcwar.*:
    description: Gives access to all MarcWar commands
    children:
      marcwar.setspawn: true
      marcwar.setflag: true
  marcwar.setspawn:
    description: Allow player to set the spawn for each team
    default: op
  marcwar.setflag:
    description: Allow player to set the flag for red team
    default: op
  marcwar.setcapture:
    description: Allow player to set the capture for blue team
    default: op
  marcwar.setlobby:
    description: Allow player to set the lobby
    default: op
  marcwar.startgame:
    description: Allow player to start the game
    default: op